kind: Service
apiVersion: v1
metadata:
  name: magenta-cli
  namespace: {{ .magenta.namespace }}
  labels:
    app: magenta-cli
    tier: frontend
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app: magenta-cli
    tier: frontend