before_script:
   - export LS_CI_TEMP=`pwd`/`mktemp -d ls-ci.XXXXXXXX`
   - export MAGENTA_ENV_BRANCH=$(if [ "$CI_COMMIT_REF_NAME" == "master" ]; then echo "master"; else echo "develop"; fi)
   - ssh-agent bash -c "ssh-add ~/build_keys/id_rsa; git clone -b $MAGENTA_ENV_BRANCH git@gitlab.com:leapsight-lojack/magenta-env.git $LS_CI_TEMP"
   - export LS_SCRIPTS=$LS_CI_TEMP/build
   - source $LS_SCRIPTS/before.sh

publish1:
 stage: publish
 tags:
   - packet
 script:
   - $LS_SCRIPTS/publish.sh

deploy1:
 stage: deploy
 tags:
   - packet
 script:
   - $LS_SCRIPTS/deploy.sh

stages:
  - publish
  - deploy
