FROM node:8-alpine

LABEL maintainer="Javier Bucar <javier.bucar@leapsight.com>" \
      version="2.2.3" \
      base="node:6"

# Basic app setup
CMD ["npm", "start" ]
EXPOSE 8080
ENV HOMEAPP=/home/node/app \
	BASE_API_URL="http://localhost:18080/" \
	CLIENT_KEY="key" \
	CLIENT_SECRET="secret"

WORKDIR $HOMEAPP

# Install node dependencies
COPY . $HOMEAPP
RUN npm i yarn && \
	yarn install && \
	yarn build:static && \
	mkdir /out

RUN cp -a ./dist/* /out/
