/* Login */
export const CHANGE_FORM = 'CHANGE_FORM';
export const SET_AUTH = 'SET_AUTH';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESSFUL = 'LOGOUT_SUCCESSFUL';
export const LOGIN_REQUEST_ERROR = 'REQUEST_ERROR';
export const LOGIN_CLEAR_ERROR = 'LOGIN_CLEAR_ERROR';
export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';
export const BACKGROUND_LOGIN = 'BACKGROUND_LOGIN';
export const BACKGROUND_LOGIN_SUCCESS = 'BACKGROUND_LOGIN_SUCCESS';

/* Things constants */
export const UPDATE_THINGS = 'UPDATE_THINGS';
export const UPDATE_THINGS_SUCCESSFUL = 'UPDATE_THINGS_SUCCESSFUL';
export const UPDATE_THINGS_ERROR = 'UPDATE_THINGS_ERROR';
export const REFRESH_THING = 'REFRESH_THING';
export const REFRESH_THING_SUCCESS = 'REFRESH_THING_SUCCESS';
export const UPDATE_THING_CONFIG = 'UPDATE_THING_CONFIG';
export const UPDATE_THING_CONFIG_SUCCESS = 'UPDATE_THING_CONFIG_SUCCESS';
export const UPDATE_THING_CONFIG_ERROR = 'UPDATE_THING_CONFIG_ERROR';
export const GET_TRIP_LIST = 'GET_TRIP_LIST ';
export const GET_TRIP_LIST_SUCCESS = 'GET_TRIP_LIST_SUCCESS';
export const RESET_TRIPS_LIST = 'RESET_TRIPS_LIST';
export const GET_SIGNALS = 'GET_SIGNALS';
export const GET_SIGNALS_SUCCESS = 'GET_SIGNALS_SUCCESS';
export const GET_CAMERAS = 'GET_CAMERAS';
export const GET_CAMERAS_SUCCESS = 'GET_CAMERAS_SUCCESS';
export const UPDATE_CAMERA = 'UPDATE_CAMERA';
export const UPDATE_CAMERA_SUCCESS = 'UPDATE_CAMERA_SUCCESS';
export const UPDATE_CAMERA_ERROR = 'UPDATE_CAMERA_ERROR';
export const DELETE_CAMERA = 'DELETE_CAMERA';
export const DELETE_CAMERA_SUCCESS = 'DELETE_CAMERA_SUCCESS';
export const DELETE_CAMERA_ERROR = 'DELETE_CAMERA_ERROR';
export const UPDATE_HOME_CONTROL_THINGS = 'UPDATE_HOME_CONTROL_THINGS';
export const UPDATE_HOME_CONTROL_THINGS_SUCCESS = 'UPDATE_HOME_CONTROL_THINGS_SUCCESS';
export const HOME_CONTROL_SWITCH = 'HOME_CONTROL_SWITCH';
export const HOME_CONTROL_SWITCH_SUCCESS = 'HOME_CONTROL_SWITCH_SUCCESS';
export const HOME_CONTROL_SWITCH_ERROR = 'HOME_CONTROL_SWITCH_ERROR';
export const HOME_CONTROL_SET_FIRSTLOAD = 'HOME_CONTROL_SET_FIRSTLOAD';

/* Geofences constants */
export const UPDATE_GEOFENCES = 'UPDATE_GEOFENCES';
export const UPDATE_GEOFENCES_SUCCESSFUL = 'UPDATE_GEOFENCES_SUCCESSFUL';
export const UPDATE_GEOFENCES_ERROR = 'UPDATE_GEOFENCES_ERROR';
export const CREATE_GEOFENCE = 'CREATE_GEOFENCE';
export const CREATE_GEOFENCE_SUCCESS = 'CREATE_GEOFENCE_SUCCESS';
export const DELETE_GEOFENCE = 'DELETE_GEOFENCE';
export const DELETE_GEOFENCE_SUCCESS = 'DELETE_GEOFENCE_SUCCESS';

/* UserData constants */
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESSFUL = 'GET_USER_DATA_SUCCESSFUL';
export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICES_SUCCESS = 'GET_DEVICES_SUCCESS';
export const REVOKE_DEVICE = 'REVOKE_DEVICE';
export const REVOKE_DEVICE_SUCCESS = 'REVOKE_DEVICE_SUCCESS';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERORR';
export const CHANGE_PIN = 'CHANGE_PIN';
export const CHANGE_PIN_SUCCESS = 'CHANGE_PIN_SUCCESS';
export const CHANGE_PIN_ERROR = 'CHANGE_PIN_ERROR';

/* Agents constants */
export const GET_AGENTS = 'GET_AGENTS';
export const GET_AGENTS_SUCCESSFUL = 'GET_AGENTS_SUCCESSFUL';
export const ADD_AGENT = 'ADD_AGENT';
export const ADD_AGENT_SUCCESS = 'ADD_AGENT_SUCCESS';
export const DELETE_AGENT = 'DELETE_AGENT';
export const DELETE_AGENT_SUCCESS = 'DELETE_AGENT_SUCCESS';
export const ASSIGN_GEOFENCE = 'ASSIGN_GEOFENCE';
export const ASSIGN_GEOFENCE_SUCCESS = 'ASSIGN_GEOFENCE_SUCCESS';
export const ASSIGN_GEOFENCE_ERROR = 'ASSIGN_GEOFENCE_ERROR';
export const UPDATE_GEOFENCE_LOCATION = 'UPDATE_GEOFENCE_LOCATION';
export const UPDATE_GEOFENCE_LOCATION_ERROR = 'UPDATE_GEOFENCE_LOCATION_ERROR';
export const UPDATE_GEOFENCE_LOCATION_SUCCESS = 'UPDATE_GEOFENCE_LOCATION_SUCCESS';
export const UPDATE_AGENT_SUCCESS = 'UPDATE_AGENT_SUCCESS';
export const DEACTIVATE_GEOFENCE = 'DEACTIVATE_GEOFENCE';
export const DEACTIVATE_GEOFENCE_SUCCESS = 'DEACTIVATE_GEOFENCE_SUCCESS';
export const CREATE_AGENT_SL = 'CREATE_AGENT_SL';
export const CREATE_AGENT_SL_SUCCESS = 'CREATE_AGENT_SL_SUCCESS';
export const CREATE_AGENT_SL_ERROR = 'CREATE_AGENT_SL_ERROR';
export const REMOVE_AGENT_SL = 'REMOVE_AGENT_SL';
export const REMOVE_AGENT_SL_SUCCESS = 'REMOVE_AGENT_SL_SUCCESS';
export const UPDATE_AGENT_SL = 'UPDATE_AGENT_SL';
export const SET_PARKING_MODE = 'SET_PARKING_MODE';
export const SET_PARKING_MODE_SUCCESS = 'SET_PARKING_MODE_SUCCESS';
export const UNSET_PARKING_MODE = 'UNSET_PARKING_MODE';
export const UNSET_PARKING_MODE_SUCCESS = 'UNSET_PARKING_MODE_SUCCESS';

/* LocationHistory */
export const GET_LOCAL_HISTORY = 'GET_LOCAL_HISTORY';
export const GET_LOCAL_HISTORY_SUCCESFUL = 'GET_LOCAL_HISTORY_SUCCESFUL';
export const UPDATE_LOCAL_HISTORY_SUCCESFUL = 'UPDATE_LOCAL_HISTORY_SUCCESFUL';
export const SELECT_LOCATIONS = 'SELECT_LOCATIONS';
export const SELECT_LOCATIONS_SUCCESFUL = 'SELECT_LOCATIONS_SUCCESFUL';
export const RESET_LOCAL_HISTORY = 'RESET_LOCAL_HISTORY';
export const SELECT_LOCATION_ID = 'SELECT_LOCATION_ID';

/* Trips constants */
export const UPDATE_TRIPS_SUCCESSFUL = 'UPDATE_TRIPS_SUCCESSFUL';
export const UPDATE_THING_TRIPS = 'UPDATE_THING_TRIPS';
export const UPDATE_THING_TRIPS_SUCCESSFUL = 'UPDATE_THING_TRIPS_SUCCESSFUL';
export const UPDATE_THING_TRIPS_ERROR = 'UPDATE_THING_TRIPS_ERROR';
export const SELECT_TRIP = 'SELECT_TRIP';
export const CHANGE_RANGE_SEGMENT = 'CHANGE_RANGE_SEGMENT';
export const MORE_TRIPS = 'MORE_TRIPS';

/* ServiceAgenda constants */
export const GET_REMINDERS = 'GET_REMINDERS';
export const GET_REMINDERS_SUCCESSFUL = 'GET_REMINDERS_SUCCESSFUL';
export const MARK_SERVICE_DONE = 'MARK_SERVICE_DONE';
export const MARK_SERVICE_DONE_SUCCESS = 'MARK_SERVICE_DONE_SUCCESS';
export const CHANGE_REMINDER_CONFIG = 'CHANGE_REMINDER_CONFIG';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const DELETE_REMINDER_SUCCESS = 'DELETE_REMINDER_SUCCESS';
export const REMINDERS_LOADING = 'REMINDERS_LOADING';
export const REMINDERS_LOADING_ERROR = 'REMINDERS_LOADING_ERROR';
export const REMINDERS_RESET = 'REMINDERS_RESET';
export const REMINDERS_GET_HISTORY_ITEMS = 'REMINDERS_GET_HISTORY_ITEMS';
export const REMINDERS_GET_HISTORY_ITEMS_SUCCESS = 'REMINDERS_GET_HISTORY_ITEMS_SUCCESS';

/* ServiceAgenda services tab constants */
export const ADD_REMINDERS = 'ADD_REMINDERS';
export const ADD_REMINDERS_SUCCESSFUL = 'ADD_REMINDERS_SUCCESSFUL';
export const ADD_REMINDERS_ERROR = 'ADD_REMINDERS_ERROR';

/* MenuPanel constants */
export const SHOW_CONFIGURATION_PANEL = 'SHOW_CONFIGURATION_PANEL';
export const SHOW_SERVICE_PANEL = 'SHOW_SERVICE_PANEL';
export const SHOW_PROFILE_PANEL = 'SHOW_PROFILE_PANEL';

/* LeftPanel */
export const SELECT_CARD = 'SELECT_CARD';
export const EXPAND_CARD = 'EXPAND_CARD';
export const SHOW_ALL_GEOFENCES = 'SHOW_ALL_GEOFENCES';
export const SHOW_THING_CONFIGURATION = 'SHOW_THING_CONFIGURATION';
export const SHOW_GEOFENCE_CONFIGURATION = 'SHOW_GEOFENCE_CONFIGURATION';
export const LEFT_PANEL_SET_LOADING = 'LEFT_PANEL_SET_LOADING';
export const LEFT_PANEL_UNSET_LOADING = 'LEFT_PANEL_UNSET_LOADING';

/* NavBar */
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const MARK_NOTIFICATION_AS_READ = 'MARK_NOTIFICATION_AS_READ';
export const MARK_NOTIFICATION_AS_READ_SUCCESS = 'MARK_NOTIFICATION_AS_READ_SUCCESS';
export const GET_UNREAD_NOTIFICATIONS_SUCCESS = 'GET_UNREAD_NOTIFICATIONS_SUCCESS';
export const GET_UNREAD_NOTIFICATIONS = 'GET_UNREAD_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESSFUL = 'GET_NOTIFICATIONS_SUCCESSFUL';
export const NOTIFICATION_MODAL_OPENED = 'NOTIFICATION_MODAL_OPENED';
export const NOTIFICATION_MODAL_CLOSED = 'NOTIFICATION_MODAL_CLOSED';
export const NOTIFICATION_SCREEN_OPENED = 'NOTIFICATION_SCREEN_OPENED';
export const NOTIFICATION_SCREEN_CLOSED = 'NOTIFICATION_SCREEN_CLOSED';

/* RightPanel constants */
export const SELECTED_COMPONENT = 'SELECTED_COMPONENT';
export const SELECT_TRIP_DETAILS = 'SELECT_TRIP_DETAILS';
export const UPDATE_TRIP_DETAILS_SUCCESSFUL = 'UPDATE_TRIPS_DETAILS_SUCCESSFUL';
export const CLOSE_TRIP_DETAILS = 'CLOSE_TRIP_DETAILS';

/* Service notification constants */
export const SELECT_SERVICE_NOTIFICATION = 'SELECT_SERVICE_NOTIFICATION';

/* Refresh token constants */
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_TOKEN_ERROR = 'REFRESH_TOKEN_ERROR';

/* ForgotPassword constants */
export const FORGOT_PASSWORD_REQUEST_CODE = 'FORGOT_PASSWORD_REQUEST_CODE';
export const FORGOT_PASSWORD_REQUEST_CODE_ERROR = 'FORGOT_PASSWORD_REQUEST_CODE_ERROR';
export const FORGOT_PASSWORD_REQUEST_CODE_SUCCESSFUL = 'FORGOT_PASSWORD_REQUEST_CODE_SUCCESSFUL';

export const FORGOT_PASSWORD_RESET_PASSWORD = 'FORGOT_PASSWORD_RESET_PASSWORD';
export const FORGOT_PASSWORD_RESET_PASSWORD_ERROR = 'FORGOT_PASSWORD_RESET_PASSWORD_ERROR';
export const FORGOT_PASSWORD_RESET_PASSWORD_SUCCESSFUL =
  'FORGOT_PASSWORD_RESET_PASSWORD_SUCCESSFUL';

/* Registration constants */
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const CREATE_PASSWORD = 'CREATE_PASSWORD';
export const CREATE_PIN = 'CREATE_PIN';
export const CREATE_PASSWORD_SUCCESS = 'CREATE_PASSWORD_SUCCESS';
export const CREATE_PIN_SUCCESS = 'CREATE_PIN_SUCCESS';

/* Action status constants */
export const ERROR = 'ERROR';
export const SUCCESS = 'SUCCESS';
export const RESET_ACTION_STATUS = 'RESET_ACTION_STATUS';

/* Alarm constants */
export const GET_ALARMS = 'GET_ALARMS';
export const GET_ALARMS_SUCCESS = 'GET_ALARMS_SUCCESS';
export const CREATE_ALARM = 'CREATE_ALARM';
export const CREATE_ALARM_SUCCESS = 'CREATE_ALARM_SUCCESS';
export const EDIT_ALARM = 'EDIT_ALARM';
export const EDIT_ALARM_SUCCESS = 'EDIT_ALARM_SUCCESS';
export const DELETE_ALARM = 'DELETE_ALARM';
export const DELETE_ALARM_SUCCESS = 'DELETE_ALARM_SUCCESS';
export const ALARM_ARM_SUCCESS = 'ALARM_ARM_SUCCESS';
export const ALARM_DISARM_SUCCESS = 'ALARM_DISARM_SUCCESS';

/* Family account */
export const GET_FAMILY_USERS = 'GET_FAMILY_USERS';
export const GET_FAMILY_USERS_SUCCESS = 'GET_FAMILY_USERS_SUCCESS';
export const ADD_OR_MODIFY_FAMILY_USER = 'ADD_OR_MODIFY_FAMILY_USER';
export const ADD_FAMILY_USER = 'ADD_FAMILY_USER';
export const ADD_FAMILY_USER_SUCCESS = 'ADD_FAMILY_USER_SUCCESS';
export const ADD_FAMILY_USER_ERROR = 'ADD_FAMILY_USER_ERROR';
export const DELETE_FAMILY_USER = 'DELETE_FAMILY_USER';
export const DELETE_FAMILY_USER_SUCCESS = 'DELETE_FAMILY_USER_SUCCESS';
export const MODIFY_USER = 'MODIFY_USER';
export const MODIFY_FAMILY_USER_SUCCESS = 'MODIFY_FAMILY_USER_SUCCESS';

/* Preferences */
export const GET_PREFERENCES = 'GET_PREFERENCES';
export const GET_PREFERENCES_SUCCESS = 'GET_PREFERENCES_SUCCESS';
export const UPDATE_PREFERENCES = 'UPDATE_PREFERENCES';
export const UPDATE_PREFERENCES_SUCCESS = 'UPDATE_PREFERENCES_SUCCESS';
export const RESET_PREFERENCES = 'RESET_PREFERENCES';

/* Shared locations */
export const UPDATE_SHARED_LOCATIONS = 'UPDATE_SHARED_LOCATIONS';
export const UPDATE_SHARED_LOCATIONS_SUCCESS = 'UPDATE_SHARED_LOCATIONS_SUCCESS';
export const REMOVE_SHARED_LOCATION = 'REMOVE_SHARED_LOCATION';

/* Third party services */
export const SOLIDMATION_LOGIN = 'SOLIDMATION_LOGIN';
export const SOLIDMATION_LOGIN_SUCCESS = 'SOLIDMATION_LOGIN_SUCCESS';
export const SOLIDMATION_LOGIN_FAILED = 'SOLIDMATION_LOGIN_FAILED';
export const SOLIDMATION_GET_STATUS = 'SOLIDMATION_GET_STATUS';
export const SOLIDMATION_GET_STATUS_LOGGED = 'SOLIDMATION_GET_STATUS_LOGGED';
export const SOLIDMATION_GET_STATUS_NOTLOGGED = 'SOLIDMATION_GET_STATUS_NOTLOGGED';
export const SOLIDMATION_UNLINK_ACCOUNT = 'SOLIDMATION_UNLINK_ACCOUNT';
export const SOLIDMATION_UNLINK_ACCOUNT_SUCCESS = 'SOLIDMATION_UNLINK_ACCOUNT_SUCCESS';
export const SOLIDMATION_SYNC_HOMES = 'SOLIDMATION_SYNC_HOMES';
export const SOLIDMATION_SYNC_HOMES_SUCCESS = 'SOLIDMATION_SYNC_HOMES_SUCCESS';
export const SOLIDMATION_PAIR_HOMES = 'SOLIDMATION_PAIR_HOMES';
export const SOLIDMATION_PAIR_HOMES_SUCCESS = 'SOLIDMATION_PAIR_HOMES_SUCCESS';
export const SOLIDMATION_LIST_HOMES = 'SOLIDMATION_LIST_HOMES';
export const SOLIDMATION_LIST_HOMES_SUCCESS = 'SOLIDMATION_LIST_HOMES_SUCCESS';

/* Synchronization */
export const START_BACKGROUND_SYNC = 'START_BACKGROUND_SYNC';
export const STOP_BACKGROUND_SYNC = 'STOP_BACKGROUND_SYNC';

/* Analytics */
export const ANALYTICS_SEND_EVENT = 'ANALYTICS_SEND_EVENT';

/* General app */
export const APP_IS_OFFLINE = 'APP_IS_OFFLINE';
export const APP_IS_ONLINE = 'APP_IS_ONLINE';
export const APP_FORCE_REFRESH = 'APP_FORCE_REFRESH';

/* ============
 *    Actions
 * ============

/* Fuel cut */
export const FUEL_CUT_CHECK_RUNNING_ACTION = 'FUEL_CUT_CHECK_RUNNING_ACTION';
export const FUEL_CUT_EXECUTE_ACTION = 'FUEL_CUT_EXECUTE_ACTION';

/* Alarms */
export const ALARM_CHECK_RUNNING_ACTION = 'ALARM_CHECK_RUNNING_ACTION';
export const ALARM_EXECUTE_ACTION = 'ALARM_EXECUTE_ACTION';

/* Gneric things actions */
export const CHECK_RUNNING_ACTION = 'CHECK_RUNNING_ACTION';
export const EXECUTE_ACTION = 'EXECUTE_ACTION';
export const EXECUTE_ACTION_SUCCESS = 'EXECUTE_ACTION_SUCCESS';
export const EXECUTE_ACTION_ERROR = 'EXECUTE_ACTION_ERROR';
export const EXECUTE_ACTION_CLEAN_ERROR = 'EXECUTE_ACTION_CLEAN_ERROR';


/* =======================
 *    Account and users
 * =======================

/* Account */
export const ACCOUNT_CREATE = 'ACCOUNT_CREATE';
export const ACCOUNT_CREATE_SUCCESS = 'ACCOUNT_CREATE_SUCCESS';
export const ACCOUNT_CREATE_ERROR = 'ACCOUNT_CREATE_ERROR';
export const ACCOUNT_CHECK_USERNAME = 'ACCOUNT_CHECK_USERNAME';
export const ACCOUNT_CHECK_USERNAME_SUCCESS = 'ACCOUNT_CHECK_USERNAME_SUCCESS';
export const ACCOUNT_PREVIOUS_STEP = 'ACCOUNT_PREVIOUS_STEP';
export const ACCOUNT_VERIFY_USERNAME = 'ACCOUNT_VERIFY_USERNAME';
export const ACCOUNT_VERIFY_USERNAME_SUCCESS = 'ACCOUNT_VERIFY_USERNAME_SUCCESS';
export const ACCOUNT_VERIFY_USERNAME_ERROR = 'ACCOUNT_VERIFY_USERNAME_ERROR';

/* Family Users UI */
export const FAMILY_USERS_RESET_ADD_ERROR = 'FAMILY_USERS_RESET_ADD_ERROR';
